In [3]:
# list of 10 numbers

import numpy as np
import pandas as pd

df = pd.DataFrame(np.random.randn(10, 4), columns=list('ABCD'))

          A         B         C         D
0  2.158736 -0.513597 -0.069223 -0.907364
1 -0.644961  1.498893  0.513403  0.000510
2  1.729755 -1.557036  1.879934  0.226029
3  1.460420  0.485153  0.461168 -0.164542
4 -0.000882 -0.221523  0.606131 -0.454290
5  0.219195 -0.257288  0.470999 -1.944349
6 -0.100071  0.249765  0.363883  1.528234
7  0.458971  1.175499  0.228700 -0.845559
8  0.964529  1.061382  1.271614 -0.490776
9 -1.097617 -1.220306 -0.733890 -0.469449